# Generated by Django 4.1 on 2022-08-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_expensetypefield_expense_description_expensetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expenseData',
        ),
        migrations.AddField(
            model_name='expensedata',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_data', to='expenseapp.expense'),
            preserve_default=False,
        ),
    ]
