# Generated by Django 4.1 on 2022-08-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0007_expense_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='clientId',
        ),
        migrations.AddField(
            model_name='expense',
            name='customerId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='expenseapp.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='expenseapp.profile'),
        ),
    ]
