# Generated by Django 4.1 on 2022-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_remove_expensedata_expense_expense_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
